CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    primeiro_nome VARCHAR(255) NOT NULL,
    ultimo_nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    renda DECIMAL NOT NULL,
    cep VARCHAR(255) NOT NULL,
    logradouro VARCHAR(255) NOT NULL,

    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

ALTER TABLE cliente ADD CONSTRAINT uc_cliente_cpf UNIQUE (cpf);

ALTER TABLE cliente ADD CONSTRAINT uc_cliente_email UNIQUE (email);