CREATE TABLE credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo UUID NOT NULL,
    valor DECIMAL NOT NULL,
    primeira_parcela DATE NOT NULL,
    parcelas INT NOT NULL,
    status INT NOT NULL,
    cliente_id BIGINT NOT NULL,

    CONSTRAINT pk_credito PRIMARY KEY (id)
);

ALTER TABLE credito ADD CONSTRAINT uc_credito_codigo UNIQUE (codigo);

ALTER TABLE credito ADD CONSTRAINT FK_CREDITO_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES cliente (id);