spring:
  datasource:
    url: jdbc:h2:mem:credit_app
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
